version: "2"
services:
  database:
    container_name: BotZillaDatabase
    build:
      context: ./database
      dockerfile: Database-Dockerfile
    networks:
      gis_network:
        ipv4_address: 1.1.1.2
    hostname: database
    ports:
      - "6079:5432"
    volumes:
      - "./database/src:/database/src"
      - "./database/tests:/database/tests"
      - "./database/input:/database/input"
      - "./database/pgtap:/database/pgtap"

networks:
  gis_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 1.1.1.0/24
