{
    "text" : {
        "one" : ":one:",
        "two" : ":two:",
        "three" : ":three:",
        "four" : ":four:",
        "five" : ":five:",
        "six" : ":six:",
        "seven" : ":seven:",
        "eight" : ":eight:",
        "nine" : ":nine:",
        "ten" : ":keycap_ten:",
        "ocean" : ":ocean:",
        "bomb" : ":boom:",
        "x" : ":x:",
        "fire" : ":fire:",
        "a" : ":regional_indicator_a:",
        "b" : ":regional_indicator_b:",
        "c" : ":regional_indicator_c:",
        "d" : ":regional_indicator_d:",
        "e" : ":regional_indicator_e:",
        "f" : ":regional_indicator_f:",
        "g" : ":regional_indicator_g:",
        "h" : ":regional_indicator_h:",
        "i" : ":regional_indicator_i:",
        "j" : ":regional_indicator_j:",
        "t" : ":regional_indicator_t:",
        "l" : ":regional_indicator_l:",
        "s" : ":regional_indicator_s:",
        "p" : ":regional_indicator_p:",
        "bb" : ":b:",
        "boats" : [":motorboat:", ":rowboat:", ":speedboat:", ":sailboat:"]
    },
    "ascii" : {
        "one" : "1\u20e3",
        "two" : "2\u20e3",
        "three" : "3\u20e3",
        "four" : "4\u20e3",
        "five" : "5\u20e3",
        "six" : "6\u20e3",
        "seven" : "7\u20e3",
        "eight" : "8\u20e3",
        "nine" : "9\u20e3",
        "ten" : "\\U0001f51f",
        "ocean" : "\\U0001f30a",
        "bomb" : "\\U0001f4a5",
        "x" : "\\u274c",
        "fire" : "\\U0001f525",
        "a" : "\\U0001f1e6",
        "b" : "\\U0001f1e7",
        "c" : "\\U0001f1e8",
        "d" : "\\U0001f1e9",
        "e" : "\\U0001f1ea",
        "f" : "\\U0001f1eb",
        "g" : "\\U0001f1ec",
        "h" : "\\U0001f1ed",
        "i" : "\\U0001f1ee",
        "j" : "\\U0001f1ef",
        "bb" : "\\U0001f171",
        "t" : "\\U0001f1f9",
        "l" : "\\U0001f1f1",
        "s" : "\\U0001f1f8",
        "p" : "\\U0001f1f5",
        "boats" : ["\\U0001f6e5", "\\U0001f6a3", "\\U0001f6a4", "\\u26f5"]
    }
}